
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnIa-364ECpzNY3ykaeM4WWnifa11bkg',
    authDomain: 'praktikum-mobileapp-9438e.firebaseapp.com',
    databaseURL: 'https://praktikum-mobileapp-9438e-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'praktikum-mobileapp-9438e',
    storageBucket: 'praktikum-mobileapp-9438e.appspot.com',
    messagingSenderId: '513389594528',
    appId: '1:513389594528:web:00a332fe430fe7288806c5'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH33AGPxyCyu0HL3C15N2uBMNyrYkMFRQ',
    appId: '1:513389594528:android:da61e55afcfb54a78806c5',
    messagingSenderId: '513389594528',
    projectId: 'praktikum-mobileapp-9438e',
    storageBucket: 'praktikum-mobileapp-9438e.appspot.com'
  );
}
